import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { Sparkles, ArrowRight, ShieldAlert, GraduationCap, Brain } from 'lucide-react';

const Landing = () => {
    const containerVariants = {
        hidden: { opacity: 0 },
        visible: {
            opacity: 1,
            transition: { staggerChildren: 0.15 }
        }
    };

    const itemVariants = {
        hidden: { y: 30, opacity: 0 },
        visible: {
            y: 0,
            opacity: 1,
            transition: {
                duration: 1,
                ease: [0.16, 1, 0.3, 1]
            }
        }
    };

    return (
        <motion.div
            className="main-content"
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '70vh', textAlign: 'center' }}
        >
            <header className="hero-header" style={{ padding: '2rem 0' }}>
                <div className="hero-glow" />
                <motion.div variants={itemVariants} className="hero-badge">
                    <Sparkles size={16} />
                    <span>About MATH 1014 Suite</span>
                </motion.div>
                <motion.h1 variants={itemVariants} className="hero-title">
                    Master <span className="text-gradient">Calculus II</span> <br /> with Confidence
                </motion.h1>
                <motion.p variants={itemVariants} className="hero-description" style={{ maxWidth: '600px', margin: '0 auto 2.5rem' }}>
                    Interactive step-by-step guides for MATH 1014. Explore complex Calculus II concepts through modern, AI-powered discovery.
                </motion.p>

                <motion.div variants={itemVariants} style={{ display: 'flex', gap: '1.5rem', justifyContent: 'center' }}>
                    <Link to="/topics" className="btn-reveal" style={{ textDecoration: 'none', padding: '1rem 2.5rem', fontSize: '1.1rem' }}>
                        <span>Start Learning</span>
                        <ArrowRight size={20} />
                    </Link>
                    <Link to="/about" className="btn-reset" style={{ textDecoration: 'none', padding: '1rem 2rem', fontSize: '1.1rem' }}>
                        <span>Learn More</span>
                    </Link>
                </motion.div>
            </header>

            <motion.section variants={itemVariants} style={{ marginTop: '4rem', maxWidth: '800px', width: '100%' }}>
                <div className="glass-card" style={{ padding: '2rem', display: 'flex', flexDirection: 'column', gap: '1.5rem', border: '1px solid rgba(168, 85, 247, 0.3)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', color: 'var(--primary-light)' }}>
                        <ShieldAlert size={24} />
                        <h2 style={{ fontSize: '1.25rem', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Important Disclaimer</h2>
                    </div>
                    <div style={{ textAlign: 'left', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                        <div style={{ display: 'flex', gap: '1rem', alignItems: 'flex-start' }}>
                            <Brain size={20} style={{ color: 'var(--primary-light)', flexShrink: 0, marginTop: '0.2rem' }} />
                            <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem', lineHeight: '1.6' }}>
                                <strong>AI-Generated Content:</strong> All mathematical examples and step-by-step solutions on this platform are generated by advanced AI models. While we strive for absolute accuracy, always verify with your primary course materials.
                            </p>
                        </div>
                        <div style={{ display: 'flex', gap: '1rem', alignItems: 'flex-start' }}>
                            <ShieldAlert size={20} style={{ color: 'var(--secondary-light)', flexShrink: 0, marginTop: '0.2rem' }} />
                            <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem', lineHeight: '1.6' }}>
                                <strong>Not from Lecture Notes:</strong> The problems shown here are independent practice sets and are <strong>not</strong> taken from official lecture notes or examinations.
                            </p>
                        </div>
                    </div>
                </div>
            </motion.section>

        </motion.div>
    );
};

export default Landing;
